<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="0862a6cda3852a5.jpg" />
    <None Remove="v2-8e5a05bb7aa0d3c3170f6e12f49d46a4_r.jpeg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LiveCharts.WinForms.NetCore3" Version="0.9.8" />
    <PackageReference Include="LiveCharts.Wpf.NetCore3" Version="0.9.8" />
    <PackageReference Include="ScottPlot.WinForms" Version="5.0.47" />
    <PackageReference Include="Syncfusion.SfChart.WPF" Version="28.1.35" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\成绩可视化分析\成绩可视化分析.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms.DataVisualization">
      <HintPath>C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.8\System.Windows.Forms.DataVisualization.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="0862a6cda3852a5.jpg" />
    <Resource Include="v2-8e5a05bb7aa0d3c3170f6e12f49d46a4_r.jpeg" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
